export interface HardeningDirective {
  key: string;
  value: string;
  comment: string;
}

export const HARDENED: readonly HardeningDirective[] = [
  { key: "PermitRootLogin", value: "no", comment: "Never allow direct root logins" },
  { key: "PasswordAuthentication", value: "no", comment: "Key-based authentication only" },
  { key: "KbdInteractiveAuthentication", value: "no", comment: "No keyboard-interactive (password) auth" },
  { key: "ChallengeResponseAuthentication", value: "no", comment: "Legacy alias for keyboard-interactive" },
  { key: "PubkeyAuthentication", value: "yes", comment: "Public keys are the only accepted method" },
  { key: "AuthorizedKeysFile", value: ".ssh/authorized_keys", comment: "Per-user allowed keys" },
  { key: "X11Forwarding", value: "no", comment: "Disable X11 tunneling" },
  { key: "AllowAgentForwarding", value: "no", comment: "Disable SSH agent forwarding" },
  { key: "AllowTcpForwarding", value: "no", comment: "Disable TCP port forwarding" },
  { key: "PermitEmptyPasswords", value: "no", comment: "No empty passwords" },
  { key: "MaxAuthTries", value: "3", comment: "Bounded authentication attempts" },
  { key: "MaxSessions", value: "4", comment: "Bounded concurrent sessions" },
  { key: "LoginGraceTime", value: "30", comment: "Short unauthenticated timeout (seconds)" },
  { key: "ClientAliveInterval", value: "300", comment: "Probe dead connections (seconds)" },
  { key: "ClientAliveCountMax", value: "2", comment: "Drop the connection after missed probes" },
  { key: "TCPKeepAlive", value: "no", comment: "Do not rely on TCP keepalives for liveness" },
  { key: "UsePAM", value: "yes", comment: "Keep PAM for account and session handling" },
  { key: "Protocol", value: "2", comment: "SSH2 only" },
  { key: "Port", value: "22", comment: "Default SSH port" },
  { key: "LogLevel", value: "VERBOSE", comment: "Verbose authentication logging" },
  { key: "Subsystem sftp", value: "internal-sftp", comment: "Built-in sftp only (no shell access)" },
] as const;

export interface SshEntry {
  key: string;
  value?: string;
  line: number;
}

export function parseConfig(text: string): SshEntry[] {
  const out: SshEntry[] = [];
  const rawLines = String(text ?? "").split(/\r?\n/);
  rawLines.forEach((raw, idx) => {
    const line = String(raw);
    const trimmed = line.trim();
    if (!trimmed) return;
    if (trimmed.startsWith("#")) {
      out.push({ key: "#", value: trimmed.slice(1), line: idx + 1 });
      return;
    }
    const m = /^(\S+)\s+(\S.*)$/.exec(trimmed);
    if (m) {
      out.push({ key: m[1], value: m[2], line: idx + 1 });
    } else {
      out.push({ key: trimmed, value: undefined, line: idx + 1 });
    }
  });
  return out;
}

export function renderEntries(entries: readonly SshEntry[]): string {
  return entries
    .map((e) => (e.key === "#" ? `#${e.value ?? ""}` : e.value === undefined ? e.key : `${e.key} ${e.value}`))
    .join("\n");
}

export interface AuditResult {
  missing: string[];
  weak: { key: string; value: string }[];
  ok: string[];
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function valueOf(text: string, key: string): string | undefined {
  const re = new RegExp(`^[ \\t]*${escapeRegExp(key)}(?:[ \\t]+(.*?))?[ \\t]*$`, "m");
  const m = re.exec(String(text ?? ""));
  return m ? (m[1] ?? "").trim() : undefined;
}

export function audit(text: string): AuditResult {
  const raw = String(text ?? "");
  const missing: string[] = [];
  const weak: { key: string; value: string }[] = [];
  const ok: string[] = [];
  for (const d of HARDENED) {
    const found = valueOf(raw, d.key);
    if (found === undefined) {
      missing.push(d.key);
      continue;
    }
    if (found.toLowerCase() !== d.value.toLowerCase()) weak.push({ key: d.key, value: found });
    else ok.push(d.key);
  }
  return { missing, weak, ok };
}

const HARDENED_KEYS: ReadonlySet<string> = new Set(HARDENED.map((d) => d.key));

function conflictsWithHardened(key: string): boolean {
  for (const hk of HARDENED_KEYS) {
    if (hk === key || hk.startsWith(`${key} `) || key.startsWith(`${hk} `)) return true;
  }
  return false;
}

export function renderHardened(existing?: string): string {
  const banner: string[] = [
    "# sshd_config generated by zh-ssh (ZeroHack ssh-hardener) 0.1.0",
    "# Audit with: zh-ssh audit /etc/ssh/sshd_config",
    "#",
  ];
  const core = HARDENED.map((d) => `${d.key} ${d.value}`);
  const extra: string[] = [];
  if (existing !== undefined && String(existing).trim() !== "") {
    for (const e of parseConfig(existing)) {
      if (e.key === "#" || e.key === "" || conflictsWithHardened(e.key)) continue;
      extra.push(e.value === undefined ? e.key : `${e.key} ${e.value}`);
    }
  }
  const parts = [...banner, ...core];
  if (extra.length) {
    parts.push("#", "# non-conflicting settings preserved from the existing config", ...extra);
  }
  return [...parts, ""].join("\n");
}